export const loginFormInitials = {
  company_id: '',
  email: '',
  password: '',
}

export const createBranchInitials = {
  branch_name: '',
  branch_type_id: 0,
  parent_branch_id: 0,
  address: '',
  branch_alt_phone_no: '',
  branch_head_id: 0,
  branch_phone_no: '',
  city: '',
  country: '',
  description: '',
  state: '',
  search_branch_head: '',
}
export const createDepartmentInitials = {
  branch_id: 0,
  department_head_id: 0,
  department_name: '',
  is_generic: 1,
  notes: '',
  parent_department_id: 0,
  search_branch_head: '',
}

export const createTeamInitials = {
  branch_id: 0,
  description: '',
  team_head_id: 0,
  team_members: [] as string[],
  team_name: '',
  search_branch_head: '',
}

export const createEmployeeInitials = {
  first_name: '',
  last_name: '',
  email: '',
  gender: '',
  date_of_birth: null as unknown as Date,
  login_access: true,
  blood_group: '',
  nationality: '',
  religion: '',
  marital_status: '',
  employee_type_id: null,
  pin: null,
  employee_category_id: null,
  employee_designation_id: null,
  employee_grade_id: null,
  branch_id: null as unknown as number,
  department_id: null as unknown as number,
  custom_employee_id: '',
  state: '',
  local_government: '',
  genotype: '',
  mobile_number: '',
  next_of_kin: '',
  last_employment_date: null as unknown as Date,
  last_employer: '',
  guarantor_name: '',
  guarantor_phone_number: '',
  last_qualification: '',
  appointment_date: null as unknown as Date,
  qualification_date: null as unknown as Date,
  account_name: '',
  account_number: '',
  bank_code: '',
  account_type: '',
  country: '',
  city: '',
  salutation: '',
  address: '',
  picture: undefined as unknown as File | string | undefined,
  bank_id: 0,
  roles: [] as number[],
  pension_fund_administrator: '',
  rsa_pin: '',
  tax_id: '',
  tax_location: '',
  staff_id: '',
  alt_mobile_number: '',
  means_of_identity: '',
  id_no: '',
  id_expiration: null as unknown as Date,
  emergency_contact_name: '',
  emergency_contact_rel: '',
  emergency_contact_no: '',
  emergency_contact_address: '',
}


export const editEmployeeInitials = {
  ...createEmployeeInitials,
  id: 0,
  picture: undefined as unknown as File | string | undefined,
}
