/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin-dashboard/route'
import { Route as EssRouteRouteImport } from './routes/ess/route'
import { Route as authPathlessLayoutRouteRouteImport } from './routes/(auth)/_pathlessLayout/route'
import { Route as onboardingChangePasswordFirstSigninRouteImport } from './routes/(onboarding)/change-password-first-signin'
import { Route as onboardingGetStartedRouteImport } from './routes/(onboarding)/get-started'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin-dashboard/index'
import { Route as EssIndexRouteImport } from './routes/ess/index'
import { Route as authPathlessLayoutLoginRouteImport } from './routes/(auth)/_pathlessLayout/login'
import { Route as AdminDashboardHrmIndexRouteImport } from './routes/admin-dashboard/hrm/index'
import { Route as AdminDashboardOrganizationIndexRouteImport } from './routes/admin-dashboard/organization/index'
import { Route as AdminDashboardOrganizationBranchIndexRouteImport } from './routes/admin-dashboard/organization/branch/index'
import { Route as AdminDashboardOrganizationBranchPathlessLayoutRouteImport } from './routes/admin-dashboard/organization/branch/_pathlessLayout'
import { Route as AdminDashboardOrganizationDepartmentIndexRouteImport } from './routes/admin-dashboard/organization/department/index'
import { Route as AdminDashboardOrganizationDepartmentPathlessLayoutRouteImport } from './routes/admin-dashboard/organization/department/_pathlessLayout'
import { Route as AdminDashboardOrganizationEmployeesIndexRouteImport } from './routes/admin-dashboard/organization/employees/index'
import { Route as AdminDashboardOrganizationEmployeesPathlessLayoutRouteImport } from './routes/admin-dashboard/organization/employees/_pathlessLayout'
import { Route as AdminDashboardOrganizationReportsIndexRouteImport } from './routes/admin-dashboard/organization/reports/index'
import { Route as AdminDashboardOrganizationSystemSettingsIndexRouteImport } from './routes/admin-dashboard/organization/system-settings/index'
import { Route as AdminDashboardOrganizationSystemSettingsAccountRouteImport } from './routes/admin-dashboard/organization/system-settings/account'
import { Route as AdminDashboardOrganizationSystemSettingsEmployeeSettingsRouteImport } from './routes/admin-dashboard/organization/system-settings/employee-settings'
import { Route as AdminDashboardOrganizationTeamsIndexRouteImport } from './routes/admin-dashboard/organization/teams/index'
import { Route as AdminDashboardOrganizationTeamsPathlessLayoutRouteImport } from './routes/admin-dashboard/organization/teams/_pathlessLayout'
import { Route as AdminDashboardOrganizationBranchPathlessLayoutCreateRouteImport } from './routes/admin-dashboard/organization/branch/_pathlessLayout.create'
import { Route as AdminDashboardOrganizationBranchPathlessLayoutEditRouteImport } from './routes/admin-dashboard/organization/branch/_pathlessLayout.edit'
import { Route as AdminDashboardOrganizationDepartmentPathlessLayoutCreateRouteImport } from './routes/admin-dashboard/organization/department/_pathlessLayout.create'
import { Route as AdminDashboardOrganizationDepartmentPathlessLayoutEditRouteImport } from './routes/admin-dashboard/organization/department/_pathlessLayout.edit'
import { Route as AdminDashboardOrganizationEmployeesPathlessLayoutCreateRouteImport } from './routes/admin-dashboard/organization/employees/_pathlessLayout.create'
import { Route as AdminDashboardOrganizationEmployeesPathlessLayoutEditRouteImport } from './routes/admin-dashboard/organization/employees/_pathlessLayout.edit'
import { Route as AdminDashboardOrganizationEmployeesDetailsIdRouteImport } from './routes/admin-dashboard/organization/employees/details/$id'
import { Route as AdminDashboardOrganizationTeamsPathlessLayoutCreateRouteImport } from './routes/admin-dashboard/organization/teams/_pathlessLayout.create'
import { Route as AdminDashboardOrganizationTeamsPathlessLayoutEditRouteImport } from './routes/admin-dashboard/organization/teams/_pathlessLayout.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EssRouteRoute = EssRouteRouteImport.update({
  id: '/ess',
  path: '/ess',
  getParentRoute: () => rootRouteImport,
} as any)
const authPathlessLayoutRouteRoute = authPathlessLayoutRouteRouteImport.update({
  id: '/(auth)/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingChangePasswordFirstSigninRoute =
  onboardingChangePasswordFirstSigninRouteImport.update({
    id: '/(onboarding)/change-password-first-signin',
    path: '/change-password-first-signin',
    getParentRoute: () => rootRouteImport,
  } as any)
const onboardingGetStartedRoute = onboardingGetStartedRouteImport.update({
  id: '/(onboarding)/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const EssIndexRoute = EssIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EssRouteRoute,
} as any)
const authPathlessLayoutLoginRoute = authPathlessLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPathlessLayoutRouteRoute,
} as any)
const AdminDashboardHrmIndexRoute = AdminDashboardHrmIndexRouteImport.update({
  id: '/hrm/',
  path: '/hrm/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardOrganizationIndexRoute =
  AdminDashboardOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationBranchIndexRoute =
  AdminDashboardOrganizationBranchIndexRouteImport.update({
    id: '/organization/branch/',
    path: '/organization/branch/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationBranchPathlessLayoutRoute =
  AdminDashboardOrganizationBranchPathlessLayoutRouteImport.update({
    id: '/organization/branch/_pathlessLayout',
    path: '/organization/branch',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationDepartmentIndexRoute =
  AdminDashboardOrganizationDepartmentIndexRouteImport.update({
    id: '/organization/department/',
    path: '/organization/department/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationDepartmentPathlessLayoutRoute =
  AdminDashboardOrganizationDepartmentPathlessLayoutRouteImport.update({
    id: '/organization/department/_pathlessLayout',
    path: '/organization/department',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationEmployeesIndexRoute =
  AdminDashboardOrganizationEmployeesIndexRouteImport.update({
    id: '/organization/employees/',
    path: '/organization/employees/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationEmployeesPathlessLayoutRoute =
  AdminDashboardOrganizationEmployeesPathlessLayoutRouteImport.update({
    id: '/organization/employees/_pathlessLayout',
    path: '/organization/employees',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationReportsIndexRoute =
  AdminDashboardOrganizationReportsIndexRouteImport.update({
    id: '/organization/reports/',
    path: '/organization/reports/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationSystemSettingsIndexRoute =
  AdminDashboardOrganizationSystemSettingsIndexRouteImport.update({
    id: '/organization/system-settings/',
    path: '/organization/system-settings/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationSystemSettingsAccountRoute =
  AdminDashboardOrganizationSystemSettingsAccountRouteImport.update({
    id: '/organization/system-settings/account',
    path: '/organization/system-settings/account',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute =
  AdminDashboardOrganizationSystemSettingsEmployeeSettingsRouteImport.update({
    id: '/organization/system-settings/employee-settings',
    path: '/organization/system-settings/employee-settings',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationTeamsIndexRoute =
  AdminDashboardOrganizationTeamsIndexRouteImport.update({
    id: '/organization/teams/',
    path: '/organization/teams/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationTeamsPathlessLayoutRoute =
  AdminDashboardOrganizationTeamsPathlessLayoutRouteImport.update({
    id: '/organization/teams/_pathlessLayout',
    path: '/organization/teams',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationBranchPathlessLayoutCreateRoute =
  AdminDashboardOrganizationBranchPathlessLayoutCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AdminDashboardOrganizationBranchPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationBranchPathlessLayoutEditRoute =
  AdminDashboardOrganizationBranchPathlessLayoutEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminDashboardOrganizationBranchPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute =
  AdminDashboardOrganizationDepartmentPathlessLayoutCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () =>
      AdminDashboardOrganizationDepartmentPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute =
  AdminDashboardOrganizationDepartmentPathlessLayoutEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      AdminDashboardOrganizationDepartmentPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute =
  AdminDashboardOrganizationEmployeesPathlessLayoutCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () =>
      AdminDashboardOrganizationEmployeesPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute =
  AdminDashboardOrganizationEmployeesPathlessLayoutEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      AdminDashboardOrganizationEmployeesPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationEmployeesDetailsIdRoute =
  AdminDashboardOrganizationEmployeesDetailsIdRouteImport.update({
    id: '/organization/employees/details/$id',
    path: '/organization/employees/details/$id',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute =
  AdminDashboardOrganizationTeamsPathlessLayoutCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AdminDashboardOrganizationTeamsPathlessLayoutRoute,
  } as any)
const AdminDashboardOrganizationTeamsPathlessLayoutEditRoute =
  AdminDashboardOrganizationTeamsPathlessLayoutEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminDashboardOrganizationTeamsPathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/ess': typeof EssRouteRouteWithChildren
  '/change-password-first-signin': typeof onboardingChangePasswordFirstSigninRoute
  '/get-started': typeof onboardingGetStartedRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/ess/': typeof EssIndexRoute
  '/login': typeof authPathlessLayoutLoginRoute
  '/admin-dashboard/hrm/': typeof AdminDashboardHrmIndexRoute
  '/admin-dashboard/organization/': typeof AdminDashboardOrganizationIndexRoute
  '/admin-dashboard/organization/branch': typeof AdminDashboardOrganizationBranchPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/department': typeof AdminDashboardOrganizationDepartmentPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/employees': typeof AdminDashboardOrganizationEmployeesPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/system-settings/account': typeof AdminDashboardOrganizationSystemSettingsAccountRoute
  '/admin-dashboard/organization/system-settings/employee-settings': typeof AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute
  '/admin-dashboard/organization/teams': typeof AdminDashboardOrganizationTeamsPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/branch/': typeof AdminDashboardOrganizationBranchIndexRoute
  '/admin-dashboard/organization/department/': typeof AdminDashboardOrganizationDepartmentIndexRoute
  '/admin-dashboard/organization/employees/': typeof AdminDashboardOrganizationEmployeesIndexRoute
  '/admin-dashboard/organization/reports/': typeof AdminDashboardOrganizationReportsIndexRoute
  '/admin-dashboard/organization/system-settings/': typeof AdminDashboardOrganizationSystemSettingsIndexRoute
  '/admin-dashboard/organization/teams/': typeof AdminDashboardOrganizationTeamsIndexRoute
  '/admin-dashboard/organization/branch/create': typeof AdminDashboardOrganizationBranchPathlessLayoutCreateRoute
  '/admin-dashboard/organization/branch/edit': typeof AdminDashboardOrganizationBranchPathlessLayoutEditRoute
  '/admin-dashboard/organization/department/create': typeof AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute
  '/admin-dashboard/organization/department/edit': typeof AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute
  '/admin-dashboard/organization/employees/create': typeof AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute
  '/admin-dashboard/organization/employees/edit': typeof AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute
  '/admin-dashboard/organization/employees/details/$id': typeof AdminDashboardOrganizationEmployeesDetailsIdRoute
  '/admin-dashboard/organization/teams/create': typeof AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute
  '/admin-dashboard/organization/teams/edit': typeof AdminDashboardOrganizationTeamsPathlessLayoutEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password-first-signin': typeof onboardingChangePasswordFirstSigninRoute
  '/get-started': typeof onboardingGetStartedRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/ess': typeof EssIndexRoute
  '/login': typeof authPathlessLayoutLoginRoute
  '/admin-dashboard/hrm': typeof AdminDashboardHrmIndexRoute
  '/admin-dashboard/organization': typeof AdminDashboardOrganizationIndexRoute
  '/admin-dashboard/organization/branch': typeof AdminDashboardOrganizationBranchIndexRoute
  '/admin-dashboard/organization/department': typeof AdminDashboardOrganizationDepartmentIndexRoute
  '/admin-dashboard/organization/employees': typeof AdminDashboardOrganizationEmployeesIndexRoute
  '/admin-dashboard/organization/system-settings/account': typeof AdminDashboardOrganizationSystemSettingsAccountRoute
  '/admin-dashboard/organization/system-settings/employee-settings': typeof AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute
  '/admin-dashboard/organization/teams': typeof AdminDashboardOrganizationTeamsIndexRoute
  '/admin-dashboard/organization/reports': typeof AdminDashboardOrganizationReportsIndexRoute
  '/admin-dashboard/organization/system-settings': typeof AdminDashboardOrganizationSystemSettingsIndexRoute
  '/admin-dashboard/organization/branch/create': typeof AdminDashboardOrganizationBranchPathlessLayoutCreateRoute
  '/admin-dashboard/organization/branch/edit': typeof AdminDashboardOrganizationBranchPathlessLayoutEditRoute
  '/admin-dashboard/organization/department/create': typeof AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute
  '/admin-dashboard/organization/department/edit': typeof AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute
  '/admin-dashboard/organization/employees/create': typeof AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute
  '/admin-dashboard/organization/employees/edit': typeof AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute
  '/admin-dashboard/organization/employees/details/$id': typeof AdminDashboardOrganizationEmployeesDetailsIdRoute
  '/admin-dashboard/organization/teams/create': typeof AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute
  '/admin-dashboard/organization/teams/edit': typeof AdminDashboardOrganizationTeamsPathlessLayoutEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/ess': typeof EssRouteRouteWithChildren
  '/(auth)/_pathlessLayout': typeof authPathlessLayoutRouteRouteWithChildren
  '/(onboarding)/change-password-first-signin': typeof onboardingChangePasswordFirstSigninRoute
  '/(onboarding)/get-started': typeof onboardingGetStartedRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/ess/': typeof EssIndexRoute
  '/(auth)/_pathlessLayout/login': typeof authPathlessLayoutLoginRoute
  '/admin-dashboard/hrm/': typeof AdminDashboardHrmIndexRoute
  '/admin-dashboard/organization/': typeof AdminDashboardOrganizationIndexRoute
  '/admin-dashboard/organization/branch/_pathlessLayout': typeof AdminDashboardOrganizationBranchPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/department/_pathlessLayout': typeof AdminDashboardOrganizationDepartmentPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/employees/_pathlessLayout': typeof AdminDashboardOrganizationEmployeesPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/system-settings/account': typeof AdminDashboardOrganizationSystemSettingsAccountRoute
  '/admin-dashboard/organization/system-settings/employee-settings': typeof AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute
  '/admin-dashboard/organization/teams/_pathlessLayout': typeof AdminDashboardOrganizationTeamsPathlessLayoutRouteWithChildren
  '/admin-dashboard/organization/branch/': typeof AdminDashboardOrganizationBranchIndexRoute
  '/admin-dashboard/organization/department/': typeof AdminDashboardOrganizationDepartmentIndexRoute
  '/admin-dashboard/organization/employees/': typeof AdminDashboardOrganizationEmployeesIndexRoute
  '/admin-dashboard/organization/reports/': typeof AdminDashboardOrganizationReportsIndexRoute
  '/admin-dashboard/organization/system-settings/': typeof AdminDashboardOrganizationSystemSettingsIndexRoute
  '/admin-dashboard/organization/teams/': typeof AdminDashboardOrganizationTeamsIndexRoute
  '/admin-dashboard/organization/branch/_pathlessLayout/create': typeof AdminDashboardOrganizationBranchPathlessLayoutCreateRoute
  '/admin-dashboard/organization/branch/_pathlessLayout/edit': typeof AdminDashboardOrganizationBranchPathlessLayoutEditRoute
  '/admin-dashboard/organization/department/_pathlessLayout/create': typeof AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute
  '/admin-dashboard/organization/department/_pathlessLayout/edit': typeof AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute
  '/admin-dashboard/organization/employees/_pathlessLayout/create': typeof AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute
  '/admin-dashboard/organization/employees/_pathlessLayout/edit': typeof AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute
  '/admin-dashboard/organization/employees/details/$id': typeof AdminDashboardOrganizationEmployeesDetailsIdRoute
  '/admin-dashboard/organization/teams/_pathlessLayout/create': typeof AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute
  '/admin-dashboard/organization/teams/_pathlessLayout/edit': typeof AdminDashboardOrganizationTeamsPathlessLayoutEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/ess'
    | '/change-password-first-signin'
    | '/get-started'
    | '/admin-dashboard/'
    | '/ess/'
    | '/login'
    | '/admin-dashboard/hrm/'
    | '/admin-dashboard/organization/'
    | '/admin-dashboard/organization/branch'
    | '/admin-dashboard/organization/department'
    | '/admin-dashboard/organization/employees'
    | '/admin-dashboard/organization/system-settings/account'
    | '/admin-dashboard/organization/system-settings/employee-settings'
    | '/admin-dashboard/organization/teams'
    | '/admin-dashboard/organization/branch/'
    | '/admin-dashboard/organization/department/'
    | '/admin-dashboard/organization/employees/'
    | '/admin-dashboard/organization/reports/'
    | '/admin-dashboard/organization/system-settings/'
    | '/admin-dashboard/organization/teams/'
    | '/admin-dashboard/organization/branch/create'
    | '/admin-dashboard/organization/branch/edit'
    | '/admin-dashboard/organization/department/create'
    | '/admin-dashboard/organization/department/edit'
    | '/admin-dashboard/organization/employees/create'
    | '/admin-dashboard/organization/employees/edit'
    | '/admin-dashboard/organization/employees/details/$id'
    | '/admin-dashboard/organization/teams/create'
    | '/admin-dashboard/organization/teams/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password-first-signin'
    | '/get-started'
    | '/admin-dashboard'
    | '/ess'
    | '/login'
    | '/admin-dashboard/hrm'
    | '/admin-dashboard/organization'
    | '/admin-dashboard/organization/branch'
    | '/admin-dashboard/organization/department'
    | '/admin-dashboard/organization/employees'
    | '/admin-dashboard/organization/system-settings/account'
    | '/admin-dashboard/organization/system-settings/employee-settings'
    | '/admin-dashboard/organization/teams'
    | '/admin-dashboard/organization/reports'
    | '/admin-dashboard/organization/system-settings'
    | '/admin-dashboard/organization/branch/create'
    | '/admin-dashboard/organization/branch/edit'
    | '/admin-dashboard/organization/department/create'
    | '/admin-dashboard/organization/department/edit'
    | '/admin-dashboard/organization/employees/create'
    | '/admin-dashboard/organization/employees/edit'
    | '/admin-dashboard/organization/employees/details/$id'
    | '/admin-dashboard/organization/teams/create'
    | '/admin-dashboard/organization/teams/edit'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/ess'
    | '/(auth)/_pathlessLayout'
    | '/(onboarding)/change-password-first-signin'
    | '/(onboarding)/get-started'
    | '/admin-dashboard/'
    | '/ess/'
    | '/(auth)/_pathlessLayout/login'
    | '/admin-dashboard/hrm/'
    | '/admin-dashboard/organization/'
    | '/admin-dashboard/organization/branch/_pathlessLayout'
    | '/admin-dashboard/organization/department/_pathlessLayout'
    | '/admin-dashboard/organization/employees/_pathlessLayout'
    | '/admin-dashboard/organization/system-settings/account'
    | '/admin-dashboard/organization/system-settings/employee-settings'
    | '/admin-dashboard/organization/teams/_pathlessLayout'
    | '/admin-dashboard/organization/branch/'
    | '/admin-dashboard/organization/department/'
    | '/admin-dashboard/organization/employees/'
    | '/admin-dashboard/organization/reports/'
    | '/admin-dashboard/organization/system-settings/'
    | '/admin-dashboard/organization/teams/'
    | '/admin-dashboard/organization/branch/_pathlessLayout/create'
    | '/admin-dashboard/organization/branch/_pathlessLayout/edit'
    | '/admin-dashboard/organization/department/_pathlessLayout/create'
    | '/admin-dashboard/organization/department/_pathlessLayout/edit'
    | '/admin-dashboard/organization/employees/_pathlessLayout/create'
    | '/admin-dashboard/organization/employees/_pathlessLayout/edit'
    | '/admin-dashboard/organization/employees/details/$id'
    | '/admin-dashboard/organization/teams/_pathlessLayout/create'
    | '/admin-dashboard/organization/teams/_pathlessLayout/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  EssRouteRoute: typeof EssRouteRouteWithChildren
  authPathlessLayoutRouteRoute: typeof authPathlessLayoutRouteRouteWithChildren
  onboardingChangePasswordFirstSigninRoute: typeof onboardingChangePasswordFirstSigninRoute
  onboardingGetStartedRoute: typeof onboardingGetStartedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ess': {
      id: '/ess'
      path: '/ess'
      fullPath: '/ess'
      preLoaderRoute: typeof EssRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_pathlessLayout': {
      id: '/(auth)/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/change-password-first-signin': {
      id: '/(onboarding)/change-password-first-signin'
      path: '/change-password-first-signin'
      fullPath: '/change-password-first-signin'
      preLoaderRoute: typeof onboardingChangePasswordFirstSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/get-started': {
      id: '/(onboarding)/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof onboardingGetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/'
      fullPath: '/admin-dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/ess/': {
      id: '/ess/'
      path: '/'
      fullPath: '/ess/'
      preLoaderRoute: typeof EssIndexRouteImport
      parentRoute: typeof EssRouteRoute
    }
    '/(auth)/_pathlessLayout/login': {
      id: '/(auth)/_pathlessLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPathlessLayoutLoginRouteImport
      parentRoute: typeof authPathlessLayoutRouteRoute
    }
    '/admin-dashboard/hrm/': {
      id: '/admin-dashboard/hrm/'
      path: '/hrm'
      fullPath: '/admin-dashboard/hrm/'
      preLoaderRoute: typeof AdminDashboardHrmIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/': {
      id: '/admin-dashboard/organization/'
      path: '/organization'
      fullPath: '/admin-dashboard/organization/'
      preLoaderRoute: typeof AdminDashboardOrganizationIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/branch/': {
      id: '/admin-dashboard/organization/branch/'
      path: '/organization/branch'
      fullPath: '/admin-dashboard/organization/branch/'
      preLoaderRoute: typeof AdminDashboardOrganizationBranchIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/branch/_pathlessLayout': {
      id: '/admin-dashboard/organization/branch/_pathlessLayout'
      path: '/organization/branch'
      fullPath: '/admin-dashboard/organization/branch'
      preLoaderRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/department/': {
      id: '/admin-dashboard/organization/department/'
      path: '/organization/department'
      fullPath: '/admin-dashboard/organization/department/'
      preLoaderRoute: typeof AdminDashboardOrganizationDepartmentIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/department/_pathlessLayout': {
      id: '/admin-dashboard/organization/department/_pathlessLayout'
      path: '/organization/department'
      fullPath: '/admin-dashboard/organization/department'
      preLoaderRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/employees/': {
      id: '/admin-dashboard/organization/employees/'
      path: '/organization/employees'
      fullPath: '/admin-dashboard/organization/employees/'
      preLoaderRoute: typeof AdminDashboardOrganizationEmployeesIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/employees/_pathlessLayout': {
      id: '/admin-dashboard/organization/employees/_pathlessLayout'
      path: '/organization/employees'
      fullPath: '/admin-dashboard/organization/employees'
      preLoaderRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/reports/': {
      id: '/admin-dashboard/organization/reports/'
      path: '/organization/reports'
      fullPath: '/admin-dashboard/organization/reports/'
      preLoaderRoute: typeof AdminDashboardOrganizationReportsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/system-settings/': {
      id: '/admin-dashboard/organization/system-settings/'
      path: '/organization/system-settings'
      fullPath: '/admin-dashboard/organization/system-settings/'
      preLoaderRoute: typeof AdminDashboardOrganizationSystemSettingsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/system-settings/account': {
      id: '/admin-dashboard/organization/system-settings/account'
      path: '/organization/system-settings/account'
      fullPath: '/admin-dashboard/organization/system-settings/account'
      preLoaderRoute: typeof AdminDashboardOrganizationSystemSettingsAccountRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/system-settings/employee-settings': {
      id: '/admin-dashboard/organization/system-settings/employee-settings'
      path: '/organization/system-settings/employee-settings'
      fullPath: '/admin-dashboard/organization/system-settings/employee-settings'
      preLoaderRoute: typeof AdminDashboardOrganizationSystemSettingsEmployeeSettingsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/teams/': {
      id: '/admin-dashboard/organization/teams/'
      path: '/organization/teams'
      fullPath: '/admin-dashboard/organization/teams/'
      preLoaderRoute: typeof AdminDashboardOrganizationTeamsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/teams/_pathlessLayout': {
      id: '/admin-dashboard/organization/teams/_pathlessLayout'
      path: '/organization/teams'
      fullPath: '/admin-dashboard/organization/teams'
      preLoaderRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/branch/_pathlessLayout/create': {
      id: '/admin-dashboard/organization/branch/_pathlessLayout/create'
      path: '/create'
      fullPath: '/admin-dashboard/organization/branch/create'
      preLoaderRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutCreateRouteImport
      parentRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutRoute
    }
    '/admin-dashboard/organization/branch/_pathlessLayout/edit': {
      id: '/admin-dashboard/organization/branch/_pathlessLayout/edit'
      path: '/edit'
      fullPath: '/admin-dashboard/organization/branch/edit'
      preLoaderRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutEditRouteImport
      parentRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutRoute
    }
    '/admin-dashboard/organization/department/_pathlessLayout/create': {
      id: '/admin-dashboard/organization/department/_pathlessLayout/create'
      path: '/create'
      fullPath: '/admin-dashboard/organization/department/create'
      preLoaderRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutCreateRouteImport
      parentRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutRoute
    }
    '/admin-dashboard/organization/department/_pathlessLayout/edit': {
      id: '/admin-dashboard/organization/department/_pathlessLayout/edit'
      path: '/edit'
      fullPath: '/admin-dashboard/organization/department/edit'
      preLoaderRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutEditRouteImport
      parentRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutRoute
    }
    '/admin-dashboard/organization/employees/_pathlessLayout/create': {
      id: '/admin-dashboard/organization/employees/_pathlessLayout/create'
      path: '/create'
      fullPath: '/admin-dashboard/organization/employees/create'
      preLoaderRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutCreateRouteImport
      parentRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutRoute
    }
    '/admin-dashboard/organization/employees/_pathlessLayout/edit': {
      id: '/admin-dashboard/organization/employees/_pathlessLayout/edit'
      path: '/edit'
      fullPath: '/admin-dashboard/organization/employees/edit'
      preLoaderRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutEditRouteImport
      parentRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutRoute
    }
    '/admin-dashboard/organization/employees/details/$id': {
      id: '/admin-dashboard/organization/employees/details/$id'
      path: '/organization/employees/details/$id'
      fullPath: '/admin-dashboard/organization/employees/details/$id'
      preLoaderRoute: typeof AdminDashboardOrganizationEmployeesDetailsIdRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin-dashboard/organization/teams/_pathlessLayout/create': {
      id: '/admin-dashboard/organization/teams/_pathlessLayout/create'
      path: '/create'
      fullPath: '/admin-dashboard/organization/teams/create'
      preLoaderRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutCreateRouteImport
      parentRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutRoute
    }
    '/admin-dashboard/organization/teams/_pathlessLayout/edit': {
      id: '/admin-dashboard/organization/teams/_pathlessLayout/edit'
      path: '/edit'
      fullPath: '/admin-dashboard/organization/teams/edit'
      preLoaderRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutEditRouteImport
      parentRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutRoute
    }
  }
}

interface AdminDashboardOrganizationBranchPathlessLayoutRouteChildren {
  AdminDashboardOrganizationBranchPathlessLayoutCreateRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutCreateRoute
  AdminDashboardOrganizationBranchPathlessLayoutEditRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutEditRoute
}

const AdminDashboardOrganizationBranchPathlessLayoutRouteChildren: AdminDashboardOrganizationBranchPathlessLayoutRouteChildren =
  {
    AdminDashboardOrganizationBranchPathlessLayoutCreateRoute:
      AdminDashboardOrganizationBranchPathlessLayoutCreateRoute,
    AdminDashboardOrganizationBranchPathlessLayoutEditRoute:
      AdminDashboardOrganizationBranchPathlessLayoutEditRoute,
  }

const AdminDashboardOrganizationBranchPathlessLayoutRouteWithChildren =
  AdminDashboardOrganizationBranchPathlessLayoutRoute._addFileChildren(
    AdminDashboardOrganizationBranchPathlessLayoutRouteChildren,
  )

interface AdminDashboardOrganizationDepartmentPathlessLayoutRouteChildren {
  AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute
  AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute
}

const AdminDashboardOrganizationDepartmentPathlessLayoutRouteChildren: AdminDashboardOrganizationDepartmentPathlessLayoutRouteChildren =
  {
    AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute:
      AdminDashboardOrganizationDepartmentPathlessLayoutCreateRoute,
    AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute:
      AdminDashboardOrganizationDepartmentPathlessLayoutEditRoute,
  }

const AdminDashboardOrganizationDepartmentPathlessLayoutRouteWithChildren =
  AdminDashboardOrganizationDepartmentPathlessLayoutRoute._addFileChildren(
    AdminDashboardOrganizationDepartmentPathlessLayoutRouteChildren,
  )

interface AdminDashboardOrganizationEmployeesPathlessLayoutRouteChildren {
  AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute
  AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute
}

const AdminDashboardOrganizationEmployeesPathlessLayoutRouteChildren: AdminDashboardOrganizationEmployeesPathlessLayoutRouteChildren =
  {
    AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute:
      AdminDashboardOrganizationEmployeesPathlessLayoutCreateRoute,
    AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute:
      AdminDashboardOrganizationEmployeesPathlessLayoutEditRoute,
  }

const AdminDashboardOrganizationEmployeesPathlessLayoutRouteWithChildren =
  AdminDashboardOrganizationEmployeesPathlessLayoutRoute._addFileChildren(
    AdminDashboardOrganizationEmployeesPathlessLayoutRouteChildren,
  )

interface AdminDashboardOrganizationTeamsPathlessLayoutRouteChildren {
  AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute
  AdminDashboardOrganizationTeamsPathlessLayoutEditRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutEditRoute
}

const AdminDashboardOrganizationTeamsPathlessLayoutRouteChildren: AdminDashboardOrganizationTeamsPathlessLayoutRouteChildren =
  {
    AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute:
      AdminDashboardOrganizationTeamsPathlessLayoutCreateRoute,
    AdminDashboardOrganizationTeamsPathlessLayoutEditRoute:
      AdminDashboardOrganizationTeamsPathlessLayoutEditRoute,
  }

const AdminDashboardOrganizationTeamsPathlessLayoutRouteWithChildren =
  AdminDashboardOrganizationTeamsPathlessLayoutRoute._addFileChildren(
    AdminDashboardOrganizationTeamsPathlessLayoutRouteChildren,
  )

interface AdminDashboardRouteRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardHrmIndexRoute: typeof AdminDashboardHrmIndexRoute
  AdminDashboardOrganizationIndexRoute: typeof AdminDashboardOrganizationIndexRoute
  AdminDashboardOrganizationBranchPathlessLayoutRoute: typeof AdminDashboardOrganizationBranchPathlessLayoutRouteWithChildren
  AdminDashboardOrganizationDepartmentPathlessLayoutRoute: typeof AdminDashboardOrganizationDepartmentPathlessLayoutRouteWithChildren
  AdminDashboardOrganizationEmployeesPathlessLayoutRoute: typeof AdminDashboardOrganizationEmployeesPathlessLayoutRouteWithChildren
  AdminDashboardOrganizationSystemSettingsAccountRoute: typeof AdminDashboardOrganizationSystemSettingsAccountRoute
  AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute: typeof AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute
  AdminDashboardOrganizationTeamsPathlessLayoutRoute: typeof AdminDashboardOrganizationTeamsPathlessLayoutRouteWithChildren
  AdminDashboardOrganizationBranchIndexRoute: typeof AdminDashboardOrganizationBranchIndexRoute
  AdminDashboardOrganizationDepartmentIndexRoute: typeof AdminDashboardOrganizationDepartmentIndexRoute
  AdminDashboardOrganizationEmployeesIndexRoute: typeof AdminDashboardOrganizationEmployeesIndexRoute
  AdminDashboardOrganizationReportsIndexRoute: typeof AdminDashboardOrganizationReportsIndexRoute
  AdminDashboardOrganizationSystemSettingsIndexRoute: typeof AdminDashboardOrganizationSystemSettingsIndexRoute
  AdminDashboardOrganizationTeamsIndexRoute: typeof AdminDashboardOrganizationTeamsIndexRoute
  AdminDashboardOrganizationEmployeesDetailsIdRoute: typeof AdminDashboardOrganizationEmployeesDetailsIdRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardHrmIndexRoute: AdminDashboardHrmIndexRoute,
  AdminDashboardOrganizationIndexRoute: AdminDashboardOrganizationIndexRoute,
  AdminDashboardOrganizationBranchPathlessLayoutRoute:
    AdminDashboardOrganizationBranchPathlessLayoutRouteWithChildren,
  AdminDashboardOrganizationDepartmentPathlessLayoutRoute:
    AdminDashboardOrganizationDepartmentPathlessLayoutRouteWithChildren,
  AdminDashboardOrganizationEmployeesPathlessLayoutRoute:
    AdminDashboardOrganizationEmployeesPathlessLayoutRouteWithChildren,
  AdminDashboardOrganizationSystemSettingsAccountRoute:
    AdminDashboardOrganizationSystemSettingsAccountRoute,
  AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute:
    AdminDashboardOrganizationSystemSettingsEmployeeSettingsRoute,
  AdminDashboardOrganizationTeamsPathlessLayoutRoute:
    AdminDashboardOrganizationTeamsPathlessLayoutRouteWithChildren,
  AdminDashboardOrganizationBranchIndexRoute:
    AdminDashboardOrganizationBranchIndexRoute,
  AdminDashboardOrganizationDepartmentIndexRoute:
    AdminDashboardOrganizationDepartmentIndexRoute,
  AdminDashboardOrganizationEmployeesIndexRoute:
    AdminDashboardOrganizationEmployeesIndexRoute,
  AdminDashboardOrganizationReportsIndexRoute:
    AdminDashboardOrganizationReportsIndexRoute,
  AdminDashboardOrganizationSystemSettingsIndexRoute:
    AdminDashboardOrganizationSystemSettingsIndexRoute,
  AdminDashboardOrganizationTeamsIndexRoute:
    AdminDashboardOrganizationTeamsIndexRoute,
  AdminDashboardOrganizationEmployeesDetailsIdRoute:
    AdminDashboardOrganizationEmployeesDetailsIdRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface EssRouteRouteChildren {
  EssIndexRoute: typeof EssIndexRoute
}

const EssRouteRouteChildren: EssRouteRouteChildren = {
  EssIndexRoute: EssIndexRoute,
}

const EssRouteRouteWithChildren = EssRouteRoute._addFileChildren(
  EssRouteRouteChildren,
)

interface authPathlessLayoutRouteRouteChildren {
  authPathlessLayoutLoginRoute: typeof authPathlessLayoutLoginRoute
}

const authPathlessLayoutRouteRouteChildren: authPathlessLayoutRouteRouteChildren =
  {
    authPathlessLayoutLoginRoute: authPathlessLayoutLoginRoute,
  }

const authPathlessLayoutRouteRouteWithChildren =
  authPathlessLayoutRouteRoute._addFileChildren(
    authPathlessLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  EssRouteRoute: EssRouteRouteWithChildren,
  authPathlessLayoutRouteRoute: authPathlessLayoutRouteRouteWithChildren,
  onboardingChangePasswordFirstSigninRoute:
    onboardingChangePasswordFirstSigninRoute,
  onboardingGetStartedRoute: onboardingGetStartedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
